### PR TITLE
MaterialSpinner supporting input hint

### PR DESCRIPTION
**Pull request by PatrickKaster**
# A MaterialSpinner supporting an input hint.

Input hint similiar to the EditText input hint concept.

## This defines:
+ ms_hint for the hint text
+ ms_hint_color for the color of the hint text's color

### CODE REVIEW

**Comment by feidi2014** [comment]
@jaredrummler can you merge @PatrickKaster's PR?

**Comment by jaredrummler** [comment]
How would this be used? The first item in the spinner would be selected, so I don't see a need for a hint.

**Comment by feidi2014** [comment]
@jaredrummler for example, when this is used for date picker, hint can be DD/MM and values start from 1-12 for month, 1-31 for date

**Comment by PatrickKaster** [comment]
@jaredrummler 

Use cases are

1. you want the user to "consciously" make a decision, not just accidentally "clicking through"

1. for some reason (maybe regulations) you cannot have a pre-selection, e.g. user has to pick a shipping service and you cannot have any of them "suggested/in advantage" by pre-selection

1. you have two spinners next to each other, e.g. origin and destination airports and you need to distinguish them.

All of the above can be definitely solved by placing a label next to the spinner. But EditTexts can also be labeled, nonetheless they have the "hint" option on input.

I am actually working on a project where UX department initially requested the hint option for the spinner, so I thought I just might share this.

**Pull request merged**
